apiVersion: apps/v1
kind: Deployment
metadata:
  name: test111
  labels:
    app: test111
  namespace: namespace-workflow-1684529004011
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test111
  template:
    metadata:
      labels:
        app: test111
    spec:
      containers:
        - name: test111
          image: acrworkflow1684529004011.azurecr.io/image-workflow-1684529004011:latest
          ports:
            - containerPort: 8000