apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1111
  labels:
    app: test1111
  namespace: namespace-workflow-1694548532254
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test1111
  template:
    metadata:
      labels:
        app: test1111
    spec:
      containers:
        - name: test1111
          image: wyregtest001.azurecr.io/image-workflow-1694548532254:latest
          ports:
            - containerPort: 8000