apiVersion: v1
kind: Service
metadata:
  name: test1111
  namespace: namespace-workflow-1694548532254
spec:
  type: LoadBalancer
  selector:
    app: test1111
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000