apiVersion: v1
kind: Service
metadata:
  name: test111
  namespace: namespace-workflow-1684529004011
spec:
  type: LoadBalancer
  selector:
    app: test111
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000